// List of all structure in the game
export const ALL_STRUCTURE_TYPES: StructureConstant[] = [
  STRUCTURE_EXTENSION,
  STRUCTURE_RAMPART,
  STRUCTURE_ROAD,
  STRUCTURE_SPAWN,
  STRUCTURE_LINK,
  STRUCTURE_WALL,
  STRUCTURE_STORAGE,
  STRUCTURE_TOWER,
  STRUCTURE_OBSERVER,
  STRUCTURE_POWER_SPAWN,
  STRUCTURE_EXTRACTOR,
  STRUCTURE_LAB,
  STRUCTURE_TERMINAL,
  STRUCTURE_CONTAINER,
  STRUCTURE_NUKER,
  STRUCTURE_KEEPER_LAIR,
  STRUCTURE_CONTROLLER,
  STRUCTURE_POWER_BANK,
  STRUCTURE_PORTAL,
  STRUCTURE_FACTORY,
  STRUCTURE_INVADER_CORE
];

// Cache ticks
export const STRUCT_CACHE_TTL = 100;
export const CONST_CACHE_TTL = 1000;