version: 2
jobs:
    test:
      docker:
        - image: circleci/node:10.16.3-stretch
        - image: mongo:latest
        - image: redis:latest
      steps:
      - checkout
      - run: npm install
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          command: npm run test
          no_output_timeout: 2h
              deploy:	
      docker:	
        - image: circleci/node:10.16.3-stretch	
      steps:	
      - checkout	
      - run: npm install	
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc	
      - run: npm publish || true	
      - run: npm run deploy
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      # TODO MISSING NPM TOKEN
      # - deploy:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: master