{
 "title": "CPU",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "room", "label": "Rooms", "query": "stats.gauges.*.rooms.*" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total usage globally",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(currentAbove(stats.gauges.*.cpu.used, 0), 2)"
    },
    {
     "target": "alias(movingAverage(currentAbove(stats.gauges.*.cpu.used, 0), 50), 'Average (50)')"
    }
   ]
  },
  {
   "title": "Total usage global head modules",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(currentAbove(stats.gauges.*.cpu.headModules.*, 0), 5)"
    },
    {
     "target": "groupByNode(alias(movingAverage(currentAbove(stats.gauges.*.cpu.headModules.*, 0), 50), 'Average (50)'), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Total usage global small modules",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(currentAbove(stats.gauges.*.cpu.smallModules, 0), 5)"
    },
    {
     "target": "groupByNode(alias(movingAverage(currentAbove(stats.gauges.*.cpu.smallModules, 0), 50), 'Average (50)'), 0, 'sum')"
    }
   ]
  },
  { "title": "Rooms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total usage in rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(currentAbove(stats.gauges.*.rooms.$room.cpu.used, 0), 4)"
    },
    {
     "target": "groupByNode(alias(movingAverage(currentAbove(stats.gauges.*.rooms.$room.cpu.used, 0), 50), 'Average (50)'), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Total usage in rooms head modules",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(aliasByNode(currentAbove(stats.gauges.*.rooms.$room.cpu.headModules.*, 0), 7), 0, 'sum')"
    },
    {
     "target": "groupByNode(alias(movingAverage(currentAbove(stats.gauges.*.rooms.$room.cpu.headModules.*, 0), 50), 'Average (50)'), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Total usage in rooms smallmodules",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(aliasByNode(currentAbove(stats.gauges.*.rooms.$room.cpu.smallModules.*, 0), 7), 0, 'sum')"
    },
    {
     "target": "groupByNode(alias(movingAverage(currentAbove(stats.gauges.*.rooms.$room.cpu.smallModules.*, 0), 50), 'Average (50)'), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Total usage in rooms creep modules",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(aliasByNode(currentAbove(stats.gauges.*.rooms.$room.cpu.creepModules, 0), 7), 0, 'sum')"
    },
    {
     "target": "groupByNode(alias(movingAverage(currentAbove(stats.gauges.*.rooms.$room.cpu.creepModules.*, 0), 50), 'Average (50)'), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Total cpu usage in rooms for roles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(aliasByNode(currentAbove(stats.gauges.*.rooms.$room.cpu.headModules.creeps.*, 0), 8), 0, 'sum')"
    },
    {
     "target": "groupByNode(alias(movingAverage(currentAbove(stats.gauges.*.rooms.$room.cpu.headModules.creeps.*, 0), 50), 'Average (50)'), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Total roles in rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(aliasByNode(currentAbove(stats.gauges.*.rooms.$room.commonMemory.creepCountByRole.*, 0), 7), 0, 'sum')"
    },
    {
     "target": "groupByNode(alias(movingAverage(currentAbove(stats.gauges.*.rooms.$room.commonMemory.creepCountByRole.*, 0), 50), 'Average (50)'), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Total usage per role per creep",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByNode(divideSeries(groupByNode(currentAbove(stats.gauges.*.rooms.$room.cpu.headModules.creeps.*, 0), 8, 'sum'), #A), 0)",
     "targetFull": "aliasByNode(divideSeries(groupByNode(currentAbove(stats.gauges.*.rooms.$room.cpu.headModules.creeps.*, 0), 8, 'sum'), groupByNode(currentAbove(stats.gauges.*.rooms.$room.commonMemory.creepCountByRole.*, 0), 6, 'sum')), 0)"
    },
    {
     "refCount": 1,
     "target": "groupByNode(alias(#E, 'Average (50)'), 0, 'sum')",
     "targetFull": "groupByNode(alias(aliasByMetric(divideSeries(movingAverage(groupByNode(currentAbove(stats.gauges.*.rooms.$room.cpu.headModules.creeps.*, 0), 8, 'sum'), 50), movingAverage(groupByNode(currentAbove(stats.gauges.*.rooms.$room.commonMemory.creepCountByRole.*, 0), 6, 'sum'), 50))), 'Average (50)'), 0, 'sum')"
    }
   ]
  }
 ]
}