{
 "title": "Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "room", "label": "Rooms", "query": "stats.gauges.*.rooms.*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(diffSeries(#A, #B), 'Net')",
     "targetFull": "alias(diffSeries(aliasByNode(sumSeries(stats.gauges.rooms.$room.performance.income.*), 5), aliasByNode(sumSeries(stats.gauges.rooms.$room.performance.expenses.*), 6, 5)), 'Net')"
    }
   ]
  },
  {
   "title": "Income",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(averageAbove(stats.gauges.rooms.$room.performance.income.*, 0.01))"
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(stats.gauges.rooms.$room.performance.expenses.*, 0.01), 6)"
    },
    {
     "target": "alias(sumSeries(averageAbove(stats.gauges.rooms.$room.performance.expenses.*.*, 0.01)), 'spawning')"
    }
   ]
  },
  { "title": "Income", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "OwnedHarvesting energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(stats.gauges.rooms.$room.performance.income.ownedHarvesting, 0.01), 3)"
    }
   ]
  },
  {
   "title": "OwnedHarvesting energy harvested percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(divideSeries(averageAbove(stats.gauges.common.energyEachTickPerSource, 0.01), #B), 0)",
     "targetFull": "aliasByNode(divideSeries(averageAbove(stats.gauges.common.energyEachTickPerSource, 0.01), divideSeries(aliasByNode(averageAbove(stats.gauges.rooms.$room.commonMemory.sourceCount, 0.01), 3), aliasByNode(averageAbove(stats.gauges.rooms.$room.performance.income.ownedHarvesting, 0.01), 3))), 0)"
    }
   ]
  },
  {
   "title": "RemoteHarvesting energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(stats.gauges.rooms.$room.performance.income.remoteHarvesting, 0.01), 3)"
    }
   ]
  },
  {
   "title": "RemoteHarvesting energy harvested percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ]
  },
  { "title": "Expenses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Spawning energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(averageAbove(stats.gauges.rooms.$room.performance.expenses.spawnExpenses.*, 0.01))"
    }
   ]
  },
  {
   "title": "Upgrading energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(stats.gauges.rooms.$room.performance.expenses.upgrading, 0.01), 3)"
    }
   ]
  },
  {
   "title": "Building energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(stats.gauges.rooms.$room.performance.expenses.building, 0.01), 3)"
    }
   ]
  },
  {
   "title": "Repairing energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(stats.gauges.rooms.$room.performance.expenses.repairing, 0.01), 3)"
    }
   ]
  },
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Creep count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(aliasByMetric(averageAbove(stats.gauges.rooms.$room.commonMemory.creepCountByRole.*, 0.01)), 0, 'sum')"
    }
   ]
  },
  {
   "title": "ConstructionSiteCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(stats.gauges.rooms.$room.commonMemory.constructionSitesCount, 0.01), 4)"
    }
   ]
  },
  { "title": "Energy storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Energy stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(aliasByMetric(averageAbove(stats.gauges.rooms.$room.energyStored.total, 0.01)), 0, 'sum')"
    },
    {
     "target": "groupByNode(aliasByMetric(averageAbove(stats.gauges.rooms.$room.energyStored.capacity, 0.01)), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Energy in storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(stats.gauges.rooms.$room.energyStored.storage, 0.01), 3)"
    }
   ]
  },
  {
   "title": "Energy in terminal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(stats.gauges.rooms.$room.energyStored.terminal, 0.01), 3)"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Controller level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageAbove(stats.gauges.rooms.$room.controller.level, 0.01), 3)"
    }
   ]
  },
  {
   "title": "Controller percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByNode(divideSeries(aliasByNode(averageAbove(stats.gauges.rooms.$room.controller.progress, 0.01), 3), #B), 0)",
     "targetFull": "aliasByNode(divideSeries(aliasByNode(averageAbove(stats.gauges.rooms.$room.controller.progress, 0.01), 3), aliasByNode(averageAbove(stats.gauges.rooms.$room.controller.progressTotal, 0.01), 3)), 0)"
    }
   ]
  }
 ]
}